version: '2'

services:
  mariadb:
    image: 'mariadb'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_DATABASE=appdb
      - MYSQL_PASSWORD=password
    volumes: 
      - ./.docker/db:/var/lib/mysql

  phpmyadmin:
    image: 'phpmyadmin'
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8181:80

  myapp:
    build: './.docker/wordpress'
    depends_on:
      - mariadb
    ports:
      - 81:3000
    volumes:
      - ./:/var/www/html
      - ./.docker/wordpress/ports.conf:/etc/apache2/ports.conf
volumes:
  myapp:
  mariadb:
